fixtures:
  repositories:
    common:
      repo: 'https://github.com/kodguru/puppet-module-common.git'
    mount:
      repo: 'https://github.com/puppetlabs/puppetlabs-mount_core.git'
    rpcbind:
      repo: 'https://github.com/ghoneycutt/puppet-module-rpcbind.git'
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    types:
      repo: 'https://github.com/kodguru/puppet-module-types.git'
